# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: federated.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'federated.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x66\x65\x64\x65rated.proto\x12\tfederated\"K\n\x0fRegisterRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x13\n\x0bnum_samples\x18\x02 \x01(\x05\x12\x12\n\nmodel_size\x18\x03 \x01(\x05\"N\n\x10RegisterResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x12\n\nmodel_size\x18\x02 \x01(\x05\x12\x15\n\rcurrent_round\x18\x03 \x01(\x05\"8\n\x0cModelRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x17\n\x0flast_seen_round\x18\x02 \x01(\x05\"g\n\rModelResponse\x12\r\n\x05round\x18\x01 \x01(\x05\x12\x0f\n\x07weights\x18\x02 \x03(\x02\x12\x19\n\x11training_complete\x18\x03 \x01(\x08\x12\x1b\n\x13min_nodes_per_round\x18\x04 \x01(\x05\"\x0f\n\rStatusRequest\"\x95\x01\n\x0eStatusResponse\x12\x15\n\rcurrent_round\x18\x01 \x01(\x05\x12\x18\n\x10registered_nodes\x18\x02 \x01(\x05\x12\x1a\n\x12updates_this_round\x18\x03 \x01(\x05\x12\x1b\n\x13last_round_avg_loss\x18\x04 \x01(\x01\x12\x19\n\x11training_complete\x18\x05 \x01(\x08\x32\xe3\x01\n\x11\x46\x65\x64\x65ratedLearning\x12G\n\x0cRegisterNode\x12\x1a.federated.RegisterRequest\x1a\x1b.federated.RegisterResponse\x12\x43\n\x0eGetGlobalModel\x12\x17.federated.ModelRequest\x1a\x18.federated.ModelResponse\x12@\n\tGetStatus\x12\x18.federated.StatusRequest\x1a\x19.federated.StatusResponseB\rZ\x0b\x66\x65\x64learn/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'federated_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\013fedlearn/pb'
  _globals['_REGISTERREQUEST']._serialized_start=30
  _globals['_REGISTERREQUEST']._serialized_end=105
  _globals['_REGISTERRESPONSE']._serialized_start=107
  _globals['_REGISTERRESPONSE']._serialized_end=185
  _globals['_MODELREQUEST']._serialized_start=187
  _globals['_MODELREQUEST']._serialized_end=243
  _globals['_MODELRESPONSE']._serialized_start=245
  _globals['_MODELRESPONSE']._serialized_end=348
  _globals['_STATUSREQUEST']._serialized_start=350
  _globals['_STATUSREQUEST']._serialized_end=365
  _globals['_STATUSRESPONSE']._serialized_start=368
  _globals['_STATUSRESPONSE']._serialized_end=517
  _globals['_FEDERATEDLEARNING']._serialized_start=520
  _globals['_FEDERATEDLEARNING']._serialized_end=747
# @@protoc_insertion_point(module_scope)
