global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "fedlearn_aggregator"
    static_configs:
      - targets: ["aggregator:9100"]
        labels:
          service: "central-aggregator"
