// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// FederatedLearningClient is the client API for FederatedLearning service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FederatedLearningClient interface {
	// RegisterNode announces a new edge node to the aggregator before
	// training starts, so the aggregator knows how many participants
	// to expect each round.
	RegisterNode(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// GetGlobalModel lets an edge node fetch the current global model
	// and round number. Edge nodes poll this after publishing an update
	// to know when the next round's weights are ready.
	GetGlobalModel(ctx context.Context, in *ModelRequest, opts ...grpc.CallOption) (*ModelResponse, error)
	// GetStatus returns aggregator-wide state, used by the CLI/dashboard.
	GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type federatedLearningClient struct {
	cc grpc.ClientConnInterface
}

func NewFederatedLearningClient(cc grpc.ClientConnInterface) FederatedLearningClient {
	return &federatedLearningClient{cc}
}

func (c *federatedLearningClient) RegisterNode(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/federated.FederatedLearning/RegisterNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *federatedLearningClient) GetGlobalModel(ctx context.Context, in *ModelRequest, opts ...grpc.CallOption) (*ModelResponse, error) {
	out := new(ModelResponse)
	err := c.cc.Invoke(ctx, "/federated.FederatedLearning/GetGlobalModel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *federatedLearningClient) GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/federated.FederatedLearning/GetStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FederatedLearningServer is the server API for FederatedLearning service.
// All implementations must embed UnimplementedFederatedLearningServer
// for forward compatibility
type FederatedLearningServer interface {
	// RegisterNode announces a new edge node to the aggregator before
	// training starts, so the aggregator knows how many participants
	// to expect each round.
	RegisterNode(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// GetGlobalModel lets an edge node fetch the current global model
	// and round number. Edge nodes poll this after publishing an update
	// to know when the next round's weights are ready.
	GetGlobalModel(context.Context, *ModelRequest) (*ModelResponse, error)
	// GetStatus returns aggregator-wide state, used by the CLI/dashboard.
	GetStatus(context.Context, *StatusRequest) (*StatusResponse, error)
	mustEmbedUnimplementedFederatedLearningServer()
}

// UnimplementedFederatedLearningServer must be embedded to have forward compatible implementations.
type UnimplementedFederatedLearningServer struct {
}

func (UnimplementedFederatedLearningServer) RegisterNode(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterNode not implemented")
}
func (UnimplementedFederatedLearningServer) GetGlobalModel(context.Context, *ModelRequest) (*ModelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGlobalModel not implemented")
}
func (UnimplementedFederatedLearningServer) GetStatus(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedFederatedLearningServer) mustEmbedUnimplementedFederatedLearningServer() {}

// UnsafeFederatedLearningServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FederatedLearningServer will
// result in compilation errors.
type UnsafeFederatedLearningServer interface {
	mustEmbedUnimplementedFederatedLearningServer()
}

func RegisterFederatedLearningServer(s *grpc.Server, srv FederatedLearningServer) {
	s.RegisterService(&_FederatedLearning_serviceDesc, srv)
}

func _FederatedLearning_RegisterNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FederatedLearningServer).RegisterNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/federated.FederatedLearning/RegisterNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FederatedLearningServer).RegisterNode(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FederatedLearning_GetGlobalModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FederatedLearningServer).GetGlobalModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/federated.FederatedLearning/GetGlobalModel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FederatedLearningServer).GetGlobalModel(ctx, req.(*ModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FederatedLearning_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FederatedLearningServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/federated.FederatedLearning/GetStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FederatedLearningServer).GetStatus(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FederatedLearning_serviceDesc = grpc.ServiceDesc{
	ServiceName: "federated.FederatedLearning",
	HandlerType: (*FederatedLearningServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterNode",
			Handler:    _FederatedLearning_RegisterNode_Handler,
		},
		{
			MethodName: "GetGlobalModel",
			Handler:    _FederatedLearning_GetGlobalModel_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _FederatedLearning_GetStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/federated.proto",
}
